apiVersion: v1
kind: Service
metadata:
  name: {{ include "incognipwn.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "incognipwn.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "incognipwn.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
