{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "incognipwn.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "incognipwn.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "incognipwn.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
{{- end -}}
